Nft mint curation
MetricsDAO/near_dbt pull request #114
Opened 2022-10-03 18:36 UTC by robel91

![nft_mint_dbt_run](https://user-images.githubusercontent.com/92173230/193652512-9595a780-d385-4e78-b91f-345971a78b37.png)

PS C:\Users\Owner\git_flipside\near_dbt> dbt test -s models\silver\silver__nft_mint.sql
18:29:34  Running with dbt=1.2.1
18:29:34  Found 32 models, 615 tests, 0 snapshots, 0 analyses, 682 macros, 1 operation, 1 seed file, 2 sources, 0 exposures, 0 metrics
18:29:34  
18:29:37  
18:29:37  Running 1 on-run-start hook
18:29:37  1 of 1 START hook: near.on-run-start.0 ......................................... [RUN]
18:29:37  1 of 1 OK hook: near.on-run-start.0 ............................................ [OK in 0.00s]
18:29:37
18:29:37  Concurrency: 4 threads (target='dev')
18:29:37
18:29:37  1 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_ACTION_ID__STRING__VARCHAR  [RUN]
18:29:37  2 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_BLOCK_ID__NUMBER__FLOAT  [RUN]
18:29:37  3 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_BLOCK_TIMESTAMP__TIMESTAMP_NTZ  [RUN]
18:29:37  4 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_NFT_ID__STRING__VARCHAR  [RUN]
18:29:40  2 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_BLOCK_ID__NUMBER__FLOAT  [PASS in 2.39s]
18:29:40  4 of 23 WARN 1 dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_NFT_ID__STRING__VARCHAR  [WARN 1 in 2.39s]
18:29:40  5 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_RECEIPT_ID__STRING__VARCHAR  [RUN]
18:29:40  6 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_RECEIVER__STRING__VARCHAR  [RUN]
18:29:40  3 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_BLOCK_TIMESTAMP__TIMESTAMP_NTZ  [PASS in 2.44s]
18:29:40  7 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_Signer__STRING__VARCHAR  [RUN]
18:29:40  1 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_ACTION_ID__STRING__VARCHAR  [PASS in 2.55s]
18:29:40  8 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_TX_HASH__STRING__VARCHAR  [RUN]
18:29:41  6 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_RECEIVER__STRING__VARCHAR  [PASS in 1.10s]
18:29:41  9 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_TX_STATUS__STRING__VARCHAR  [RUN]
18:29:41  7 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_Signer__STRING__VARCHAR  [PASS in 1.08s]
18:29:41  10 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint__INGESTED_AT__TIMESTAMP_NTZ  [RUN]
18:29:41  5 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_RECEIPT_ID__STRING__VARCHAR  [PASS in 1.18s]
18:29:41  11 of 23 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint__INSERTED_TIMESTAMP__TIMESTAMP_NTZ  [RUN]
18:29:41  8 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_TX_HASH__STRING__VARCHAR  [PASS in 1.11s]
18:29:41  12 of 23 START test not_null_silver__nft_mint_ACTION_ID ........................ [RUN]
18:29:42  12 of 23 PASS not_null_silver__nft_mint_ACTION_ID .............................. [PASS in 0.86s]
18:29:42  13 of 23 START test not_null_silver__nft_mint_BLOCK_ID ......................... [RUN]
18:29:42  9 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_TX_STATUS__STRING__VARCHAR  [PASS in 1.05s]
18:29:42  14 of 23 START test not_null_silver__nft_mint_BLOCK_TIMESTAMP .................. [RUN]
18:29:42  10 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint__INGESTED_AT__TIMESTAMP_NTZ  [PASS in 1.21s]
18:29:42  11 of 23 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint__INSERTED_TIMESTAMP__TIMESTAMP_NTZ  [PASS in 1.17s]
18:29:42  15 of 23 START test not_null_silver__nft_mint_NFT_ID ........................... [RUN]
18:29:42  16 of 23 START test not_null_silver__nft_mint_RECEIPT_ID ....................... [RUN]
18:29:43  14 of 23 PASS not_null_silver__nft_mint_BLOCK_TIMESTAMP ........................ [PASS in 0.79s]
18:29:43  17 of 23 START test not_null_silver__nft_mint_RECEIVER ......................... [RUN]
18:29:43  13 of 23 PASS not_null_silver__nft_mint_BLOCK_ID ............................... [PASS in 0.85s]
18:29:43  18 of 23 START test not_null_silver__nft_mint_Signer ........................... [RUN]
18:29:43  16 of 23 PASS not_null_silver__nft_mint_RECEIPT_ID ............................. [PASS in 0.82s]
18:29:43  19 of 23 START test not_null_silver__nft_mint_TX_HASH .......................... [RUN]
18:29:45
18:29:45  Finished running 23 tests, 1 hook in 0 hours 0 minutes and 10.37 seconds (10.37s).
18:29:45
18:29:45  Completed with 3 warnings:
18:29:45
18:29:45  Warning in test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mint_NFT_ID__STRING__VARCHAR (models\silver\silver__nft_mint.yml)    
18:29:45    Got 1 result, configured to warn if != 0
18:29:45
18:29:45    compiled SQL at target\compiled\near\models\silver\silver__nft_mint.yml\dbt_expectations_expect_column_ba4b990223b70e003f67a7887413cab5.sql
18:29:45
18:29:45  Warning in test not_null_silver__nft_mint_NFT_ID (models\silver\silver__nft_mint.yml)
18:29:45    Got 1025326 results, configured to warn if != 0
18:29:45
18:29:45    compiled SQL at target\compiled\near\models\silver\silver__nft_mint.yml\not_null_silver__nft_mint_NFT_ID.sql
18:29:45
18:29:45  Warning in test unique_silver__nft_mint_RECEIPT_ID (models\silver\silver__nft_mint.yml)
18:29:45    Got 26224 results, configured to warn if != 0
18:29:45

# Description

_Please include a summary of changes and related issue (if any)._

# Tests

- [ ] Please provide evidence of your successful `dbt run` / `dbt test` here
- [ ] Any comparison between `prod` and `dev` for any schema change

# Checklist
- [ ] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [ ] Tag the person(s) responsible for reviewing proposed changes
- [ ] Notes to deployment, if a `full-refresh` is needed for any table
- [ ] Run `git merge main` to pull any changes from remote into your branch prior to merge.

2022-10-04 10:41 UTC, D0R11 requested changes
Tested out your query and it's working well as intended but I only have a few comments to iron out the kinks. Highly suggest to check out the DBT style guide [here](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md). 

You may be missing another SQL file which should be core EZ SQL version of this one. Add that one and then commit it here and I'll check.

If you have any questions, let me know and I'll be happy to answer them.

Great work! Only a few comments and we're good to go

2022-10-04 10:41 UTC, D0R11 commented on models/silver/silver__nft_mint.sql
> +    ON A.tx_hash = R.tx_hash
Please follow the DBT style guide [here](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md). The style guide says to do away with aliases. Thanks!

2022-10-04 10:41 UTC, D0R11 commented on models/silver/silver__nft_mint.yml
> +  - name: silver__nft_mint
Change model name to plural (as stated in the [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md))

2022-10-04 10:41 UTC, D0R11 commented on models/silver/silver__nft_mint.yml
> +      - name: Signer
Small nitpick but can you capitalize this one? thanks!

2022-10-04 10:41 UTC, D0R11 commented on models/silver/silver__nft_mint.yml
> +      - name: NFT_ID
remove non-null constraint if query is expected to return null values

2022-10-04 10:41 UTC, D0R11 commented on models/silver/silver__nft_mint.yml
> +                - VARCHAR
additional columns that are not in the documentation but are in the final SQL table:

- action_index
- action_name
- method_name
- project_name
- token_id
- nft_address
- deposit
- attached_gas
- gas_used
- gas_burnt
- network_fee
- receipt_index
- receipt_outcome_id

You may remove most of the columns since they may be irrelevant to the scope of the table

2022-10-04 17:54 UTC, forgxyz commented on models/silver/silver__nft_mints.sql
> +    nft_mint as (
Is any data coming from this CTE that is not available in the subsequent function_call CTE? It looks like this is duplicative and can be eliminated to make the query run a bit faster.

2022-10-04 17:54 UTC, forgxyz commented on models/silver/silver__nft_mints.sql
> +        from {{ ref("silver__actions_events_function_call") }}
Agree with @D0R11, all ref calls should include the incremental load filter

2022-10-04 17:56 UTC, forgxyz commented on models/silver/silver__nft_mints.sql
> +    receiver,
Same as signer, no need to change the name

2022-10-04 17:56 UTC, forgxyz reviewed
A few changes requested

2022-10-05 03:19 UTC, D0R11 commented on models/silver/silver__nft_mints.sql
> +    nft_mint as (
agree

2022-10-06 01:02 UTC, D0R11 approved these changes
LGTM

2022-10-06 01:02 UTC, merged