rename columns to match NEAR
MetricsDAO/near_dbt pull request #22
Opened 2022-03-17 21:35 UTC by forgxyz

This PR renames columns in `transactions` and `events_actions` to use `txn_hash` and `block_height`, matching current NEAR nomenclature.

Both of these tables would need to be rebuilt, not simply refreshed, due to the column change.  
  
Testing:  
```
root@0d1d2327f398:/near# dbt run -m transactions
Running with dbt=0.21.1
Found 5 models, 41 tests, 0 snapshots, 0 analyses, 175 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

19:33:39 | Concurrency: 4 threads (target='dev')
19:33:39 |
19:33:39 | 1 of 1 START incremental model DEV.transactions...................... [RUN]
19:38:26 | 1 of 1 OK created incremental model DEV.transactions................. [SUCCESS 1 in 287.32s]
19:38:26 |
19:38:26 | Finished running 1 incremental model in 292.80s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

```
root@0d1d2327f398:/near# dbt run -m actions_events
Running with dbt=0.21.1
Found 5 models, 41 tests, 0 snapshots, 0 analyses, 175 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

21:31:22 | Concurrency: 4 threads (target='dev')
21:31:22 |
21:31:22 | 1 of 1 START incremental model DEV.actions_events.................... [RUN]
21:32:40 | 1 of 1 OK created incremental model DEV.actions_events............... [SUCCESS 1 in 78.05s]
21:32:40 |
21:32:40 | Finished running 1 incremental model in 84.01s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

2022-03-19 04:21 UTC, chuxinh requested changes
@forgxyz do you mind also update one more table `blocks`? would like to make sure things are consistent named across. Also need to update the documentation in corresponding `yml` files. Thank you!!

2022-03-19 04:21 UTC, chuxinh commented on models/core/txs.sql
> -{{
maybe you should remove these two deleted files from this PR, and merge this: https://github.com/MetricsDAO/near_dbt/pull/21
first otherwise there'd be a clash depending on which PR you merge first and you have to do a rebase

2022-03-19 04:21 UTC, chuxinh commented on models/core/transactions.sql
>          unique_key= 'tx_id',
this needs to be updated to `txn_hash` too

2022-03-19 04:25 UTC, forgxyz commented
Missed blocks! I'll update. And yep, I totally forgot about the documentation files. Will fix those, too.

2022-03-19 04:28 UTC, chuxinh commented
oh just realised and your `action_events` table too while i was looking at it :p

2022-03-20 11:13 UTC, chuxinh commented
@forgxyz actually don't worry about the renaming for `transactions`, i've addressed that in this PR with other changes, so don't wanna have a clash. https://github.com/MetricsDAO/near_dbt/pull/26

Would be great if you can update the one for blocks too

2022-03-21 19:37 UTC, forgxyz commented
Ok, so I will update for `blocks` and will ignore `transactions` as that is addressed in another PR.

2022-03-22 12:20 UTC, chuxinh reviewed
LGTM but pls don't merge yet as I'm sure it will fail in the current prod given the current `transaction` table hasn't updated the `tx_id` yet.
Would like either your or ant to approve this PR and merge that first before yours: https://github.com/MetricsDAO/near_dbt/pull/26

2022-03-22 12:20 UTC, chuxinh commented on models/core/transactions.sql
> +{{
do you mind reverting the changes of this file in the PR?

2022-03-22 21:56 UTC, forgxyz commented on models/core/transactions.sql
> +{{
done!

2022-03-22 21:56 UTC, forgxyz commented
`transactions.sql` reverted to original commit from main.

2022-03-23 00:09 UTC, chuxinh approved these changes
LGTM merge pending https://github.com/MetricsDAO/near_dbt/pull/26

2022-03-24 00:54 UTC, merged