Create table `actions_events_addkey`
MetricsDAO/near_dbt pull request #28
Opened 2022-03-21 23:51 UTC by forgxyz

This PR closes issue #20 by parsing the `actions_events` table for instances of `AddKey`.

2022-03-23 01:07 UTC, chuxinh requested changes

2022-03-23 01:07 UTC, chuxinh commented on models/core/actions_events_addkey.sql
> +    action_data:access_key:permission::object as permission,
i got an error when running this saying `failed to cast variant value `FullAccess` to OBJECT` which seems to apply to single string only?

2022-03-23 01:07 UTC, chuxinh commented on models/core/actions_events_addkey.sql
> +    action_data:access_key:permission:FunctionCall:allowance::float as allowance,
```suggestion
    action_data:access_key:permission:FunctionCall:allowance::number as allowance,
```

2022-03-23 01:07 UTC, chuxinh commented on models/core/actions_events_addkey.yml
> +      This table extracts all action events from a transaction and stores the argument data under action_data.
update it to be related to `AddKey` actions only?

2022-03-23 01:07 UTC, chuxinh commented on models/core/actions_events_addkey.yml
> +        description: The hash of the transaction, this is the primary key for this table.
`action_id` should be the primary key?

2022-03-23 01:07 UTC, chuxinh commented on models/core/actions_events_addkey.yml
> +          - not_null
if this could be empty, maybe remove the test here

2022-03-23 01:07 UTC, chuxinh commented on models/core/actions_events_addkey.yml
> +        tests:
remove this line

2022-03-23 01:07 UTC, chuxinh commented on models/core/actions_events_addkey.yml
> +        tests:
remove this line

2022-03-23 01:07 UTC, chuxinh commented on models/core/actions_events_addkey.yml
> +        description: the account ID of the destination of this transaction. NULL if permission is FullAccess.
```suggestion
        description: The account ID of the destination of this transaction. NULL if permission is FullAccess.
```

2022-03-23 01:07 UTC, chuxinh commented on models/core/actions_events_addkey.yml
> +        tests:
remove this line

2022-03-23 17:52 UTC, forgxyz commented on models/core/actions_events_addkey.yml
> +        description: The hash of the transaction, this is the primary key for this table.
Yes, do I need to designate something here?

2022-03-23 22:07 UTC, chuxinh commented on models/core/actions_events_addkey.yml
> +        description: The hash of the transaction, this is the primary key for this table.
nope haha you've already done that in the config at top. just need to update the description here by removing the primary key part

2022-03-23 23:14 UTC, forgxyz commented on models/core/actions_events_addkey.yml
> +        description: The hash of the transaction, this is the primary key for this table.
Ahhhh thank you

2022-04-04 20:10 UTC, forgxyz commented
I believe I addressed all of these, apologies if I missed one for re-review.

2022-04-06 09:13 UTC, chuxinh approved these changes
LGTM after nits

2022-04-06 09:13 UTC, chuxinh commented on models/core/actions_events_addkey.yml
> +      This table extracts all AkkDey events from actions and stores the argument data under action_data.
typo? `Addkey`

2022-04-06 14:25 UTC, forgxyz commented on models/core/actions_events_addkey.yml
> +      This table extracts all AkkDey events from actions and stores the argument data under action_data.
ty

2022-04-06 17:00 UTC, merged