add number of transactions table
MetricsDAO/near_dbt pull request #29
Opened 2022-03-22 02:41 UTC by 0xissui

2022-03-22 21:45 UTC, forgxyz commented
We'll need to clean up outstanding PRs so the `transaction` table is build in prod as that should be the upstream table. Otherwise, LGTM after we fix that.

2022-03-25 05:50 UTC, 0xissui commented
Updated to have `transactions` as the upstream table. 
Quick eyeball comparison between daily transactions on https://explorer.near.org/ seems very close.

2022-04-02 05:58 UTC, chuxinh requested changes

2022-04-10 05:45 UTC, chuxinh approved these changes
LGTM

2022-04-10 05:51 UTC, merged