add daily gas metrics
MetricsDAO/near_dbt pull request #33
Opened 2022-04-14 03:32 UTC by 0xissui

# Description

Add daily gas metrics for near data base

# Tests 
- [ ] Please provide evidence of your successful `dbt run` / `dbt test` here

root@4104c880a103:/near# dbt run -s metrics_daily_gas
Running with dbt=0.21.1
Found 7 models, 57 tests, 0 snapshots, 0 analyses, 174 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

22:14:23 | Concurrency: 4 threads (target='dev')
22:14:23 |
22:14:23 | 1 of 1 START incremental model DEV.metrics_daily_gas................. [RUN]
22:14:32 | 1 of 1 OK created incremental model DEV.metrics_daily_gas............ [SUCCESS 1 in 9.48s]
22:14:32 |
22:14:32 | Finished running 1 incremental model in 13.41s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

- [ ] Any comparison between `prod` and `dev` for any schema change

# Checklist
- [ ] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [ ] Tag the person(s) responsible for reviewing proposed changes 
@chuxinh or @antonyip 
- [ ] Notes to deployment, if a `full-refresh` is needed for any table

2022-04-15 19:26 UTC, forgxyz requested changes

2022-04-15 19:26 UTC, forgxyz commented on models/metrics/metrics_daily_gas.yml
> +        description: The total daily gas used in transactions.
Add a comment here that the number is not decimal adjusted (see other `yml` files for if this is 12 or 24)

2022-04-15 19:26 UTC, forgxyz commented on models/metrics/metrics_daily_gas.yml
> +        description: The average gas price in transactions.
Add a comment here that the number is not decimal adjusted (see other `yml` files for if this is 12 or 24)

2022-04-15 19:26 UTC, forgxyz commented on models/metrics/metrics_daily_gas.sql
> +select * from final
End with a blank newline

2022-04-24 00:30 UTC, chuxinh approved these changes
LGTM after nits

2022-04-24 00:30 UTC, chuxinh commented on models/metrics/metrics_daily_gas.sql
> +    where {{ incremental_last_x_days("date", 3) }}
maybe leave it for 7 days for this and line 32, I feel like there could be potential delays in data coming longer than that

2022-04-25 01:53 UTC, chuxinh commented on models/metrics/metrics_daily_gas.sql
> +}}
can you materialise this as a table instead of incremental build?

2022-04-25 10:52 UTC, chuxinh requested changes

2022-04-25 10:52 UTC, chuxinh commented on models/metrics/metrics_daily_gas.sql
> +        incremental_strategy = 'delete+insert',
can remove these two lines

2022-04-25 10:52 UTC, chuxinh commented on models/metrics/metrics_daily_gas.sql
> +    where {{ incremental_last_x_days("date", 7) }}
this line is not needed after changing materialized from incremental to table

2022-04-25 10:52 UTC, chuxinh commented on models/metrics/metrics_daily_gas.sql
> +    where {{ incremental_last_x_days("date", 7) }}
same for here

2022-04-28 12:18 UTC, chuxinh approved these changes
LGTM

2022-05-03 05:42 UTC, forgxyz approved these changes
LGTM

2022-05-03 05:42 UTC, merged