Active contracts
MetricsDAO/near_dbt pull request #83
Opened 2022-08-05 19:42 UTC by sedaghatfar

# Description

_Please include a summary of changes and related issue (if any)._
A table tracking the number of active contracts deployed

# Tests

- [ ] Please provide evidence of your successful `dbt run` / `dbt test` here
![image](https://user-images.githubusercontent.com/3936021/183148240-1af507a9-17a0-4357-a24e-5b3e397f9523.png)
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/3936021/183149235-b01de979-0f13-414b-ab00-a4f75b2f9c3e.png">

- [ ] Any comparison between `prod` and `dev` for any schema change

# Checklist
- [ ] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [ ] Tag the person(s) responsible for reviewing proposed changes
@0xissui 
- [ ] Notes to deployment, if a `full-refresh` is needed for any table
- [ ] Run `git merge main` to pull any changes from remote into your branch prior to merge.

2022-08-08 22:16 UTC, forgxyz commented
The transaction receiver is not necessarily a contract. In a P2P NEAR transfer, this method is counting individuals as contracts.

2022-08-08 23:02 UTC, sedaghatfar commented
> The transaction receiver is not necessarily a contract. In a P2P NEAR transfer, this method is counting individuals as contracts.

Correct, this is based off https://github.com/near/near-analytics/blob/main/aggregations/db_tables/daily_active_contracts_count.py in individuals using P2P are  contracts as well

2022-08-11 02:09 UTC, sedaghatfar commented
Near has a different naming system than other blockchains see here [Exploring NEAR Protocol APIs](https://github.com/near-examples/workshop--exploring-near-apis#accounts)

Example of a P2P transfer not being counted as a contract 
tx_tash - 6ahKTLaG7ga5Zh3ayUMQVmj43EnDdjauoNS23wBMuD3Z

2022-08-11 02:09 UTC, sedaghatfar commented
Near has a different naming system than other blockchains see here [Exploring NEAR Protocol APIs](https://github.com/near-examples/workshop--exploring-near-apis#accounts)

Example of a P2P transfer not being counted as a contract 
tx_tash - 6ahKTLaG7ga5Zh3ayUMQVmj43EnDdjauoNS23wBMuD3Z

2022-08-11 02:22 UTC, sedaghatfar commented
Near has a different naming system than other blockchains see here [Exploring NEAR Protocol APIs](https://github.com/near-examples/workshop--exploring-near-apis#accounts)

Example of a P2P transfer not being counted as a contract 
tx_hash - 6ahKTLaG7ga5Zh3ayUMQVmj43EnDdjauoNS23wBMuD3Z
not showing any data in the NEAR_DEV.SILVER.ACTIONS_EVENTS_FUNCTION_CALL table
same for tx_hash FD5yF6X4tbUjYtfZkPe9ZwDQby5bkQ4sTbjMrryhaMw5 transfer from sweat welcome to another address
tx_hash - Die5nz5ZLaWat52QTyUQWoG5E5TBNTCqvCsJCFfEqxqP
P2P both accounts have a name
Example that is being counted as an active contact 3qKBCCg3He2o4QufUVYVLgUrjEoaZz5fK2suqckrgzA4
using the near crowd contact

2022-08-11 02:24 UTC, sedaghatfar commented
What we might want to do is exclude method names like transfer, but could cause later metics to not match
```SELECT 
    method_name
    , COUNT(*) as transactions
    , COUNT(distinct t.tx_receiver) as distinct_receivers
FROM NEAR_DEV.SILVER.TRANSACTIONS t 
JOIN NEAR_DEV.SILVER.ACTIONS_EVENTS_FUNCTION_CALL aefc ON aefc.tx_hash = t.tx_hash
WHERE t.block_timestamp > CURRENT_DATE - 90
GROUP BY 1
ORDER BY 3 DESC
```
![image](https://user-images.githubusercontent.com/3936021/184054631-21315529-72d7-46dd-b70b-bf39a0632138.png)

2022-08-22 22:23 UTC, 0xissui requested changes
overall good after nits!

2022-08-22 22:23 UTC, 0xissui commented on models/metrics/metrics__active_contracts.sql
> +{% if is_incremental() %}
do we need this if we already set as incremental in line 2?

2022-08-22 22:23 UTC, 0xissui commented on models/metrics/metrics__active_contracts.yml
> +        description: The date (day).
Let's use the markdown tables in the descriptions folder (make one if doesn't exist yet!) 
e..g ` "{{ doc('date')}}" `

2022-08-25 01:50 UTC, sedaghatfar commented on models/metrics/metrics__active_contracts.sql
> +{% if is_incremental() %}
protective if you do a full refresh

2022-08-25 01:58 UTC, sedaghatfar commented on models/metrics/metrics__active_contracts.yml
> +        description: The date (day).
Added, thank you

2022-08-26 23:46 UTC, 0xissui approved these changes
LGTM

2022-08-29 19:38 UTC, merged