feat: nft sales tables
MetricsDAO/near_dbt pull request #98
Opened 2022-08-28 07:09 UTC by geewynn

# Description

_Please include a summary of changes and related issue (if any)._

# Tests

- [x] Please provide evidence of your successful `dbt run` / `dbt test` here
- [x] Any comparison between `prod` and `dev` for any schema change

![image](https://user-images.githubusercontent.com/29405050/187062069-8a75675d-e982-43fc-8a1c-c943c12ec74f.png)
![image](https://user-images.githubusercontent.com/29405050/187061992-b8d56956-5eba-4212-9700-ac96f17ac8a2.png)
![image](https://user-images.githubusercontent.com/29405050/187062013-cbf6f359-15ef-4626-bf04-34b134ef6a1e.png)

# Checklist
- [x] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [x] Tag the person(s) responsible for reviewing proposed changes
- [x] Notes to deployment, if a `full-refresh` is needed for any table
- [x] Run `git merge main` to pull any changes from remote into your branch prior to merge.

2022-09-07 16:38 UTC, forgxyz requested changes

2022-09-07 16:38 UTC, forgxyz commented on models/core/core__ez_nft_sales.sql
> +SELECT
We need to include the tx boilerplate here:
- tx hash
- block id
- block timestamp

2022-09-07 16:38 UTC, forgxyz commented on models/silver/silver__nft_sales.sql
> +    SELECT
We need to include the tx boilerplate here:
- tx hash
- block id
- block timestamp

2022-09-07 16:38 UTC, forgxyz commented on models/silver/silver__nft_sales.sql
> +        event = 'nft_transfer'
Did you check out other nft type events? There are some that might be related to sales

```sql
WITH txs AS (

    SELECT
        *
    FROM
        NEAR_DEV.silver.receipts
),
tx AS (
    SELECT
        REPLACE(
            VALUE,
            'EVENT_JSON:'
        ) AS json,
        TRY_PARSE_JSON(json) :event :: STRING AS event,
        TRY_PARSE_JSON(json) :data AS data_log,
        REGEXP_SUBSTR(
            status_value,
            'Success'
        ) AS reg_success,
        _ingested_at,
        _inserted_timestamp
    FROM
        txs,
        TABLE(FLATTEN(input => logs))
    WHERE
        1 = 1
        AND reg_success IS NOT NULL
        AND event IS NOT NULL
)

select distinct event from tx
where event ilike '%nft%';
```

2022-09-07 16:38 UTC, forgxyz commented on models/silver/silver__nft_sales.sql
> +        VALUE :authorized_id :: STRING AS nft_project,
Most (non null) records are `.near` addresses, but there are some integers included in here. Do you know what these records are and why a number is the authorized_id instead of an address?

2022-09-07 16:41 UTC, forgxyz commented
@geewynn note I merged main into this branch so `git pull` on your machine

2022-09-10 07:14 UTC, geewynn commented on models/silver/silver__nft_sales.sql
> +    SELECT
[ed09781](https://github.com/MetricsDAO/near_dbt/pull/98/commits/ed097818ff022fc8f5f6402921fb875316fd74b0)

2022-09-10 07:14 UTC, geewynn commented on models/core/core__ez_nft_sales.sql
> +SELECT
[ed09781](https://github.com/MetricsDAO/near_dbt/pull/98/commits/ed097818ff022fc8f5f6402921fb875316fd74b0)

2022-09-10 09:53 UTC, geewynn commented on models/silver/silver__nft_sales.sql
> +        VALUE :authorized_id :: STRING AS nft_project,
can't really say, from near doc, it's either an approval id or a marketplace approved to transfer the nft.

2023-04-21 21:21 UTC, closed without merging